name: RegionBoard
main: org.samson.bukkit.plugins.regionboard.RegionBoardPlugin
version: ${project.version}

depend: [WorldGuard]

commands:
   regionboard:
      description: RegionBoard Admin Command
      usage: |
        /<command> version - Get the plugin's version
        /<command> add <region-id> <stat> <display-name> - Create a new Region Board
        /<command> list - List the existing regions
        /<command> info <region-id> - Show the region board's info
        /<command> removeall - Remove all regions
      permission: regionboard.admin

permissions:

   regionboard.admin:
      description: Allows you to use the RegionBoard admin command
      default: op
