name: RegionBoard
main: org.samson.bukkit.plugins.regionboard.RegionBoardPlugin
version: ${project.version}

depend: [WorldGuard]

commands:
   regionboard:
      description: RegionBoard Admin Command
      usage: /<command> [version | list | add | info | reset | autoreset | remove]
      permission: regionboard.admin

permissions:

   regionboard.admin:
      description: Allows you to use the RegionBoard admin command
      default: op

   regionboard.seewinmsg:
      description: Allows you to see the auto-reset win message
      default: true
